### PR TITLE
handle service functional

### PR DESCRIPTION
**Pull request by mlhenderson**
- Switched shock port to 7044 to be more consistent with other KBase deployments.
- Had to revert to using dev_container for handle_service and handle_mngr deploys for now.
- Added python clients for Shock, Handle service.
- Added basic python tests that Handle and Shock services are up and running in the container.
- Added basic setup.py for python setup.py test functionality.
- Partial Handle manager service and workspace service installs.
- Vanilla nginx install, no proxies yet.

### CODE REVIEW

**Review by msneddon — COMMENTED** [review]
I have a few minor questions, but overall looks pretty good to me.

First, does it seem like any of this setup is impacted by @kkellerlbl's PR to the handle_service (https://github.com/kbase/handle_service/pull/31)?  Maybe @MrCreosote or @kkellerlbl can comment on whether we want that handle_service PR in soon, or what the status of that PR is.

And second, is the DB creation parameters in build/config/hsi.sql available from the handle_service repo?  If not, we should probably add that there as well, even if it is just for documentation.

**Comment by MrCreosote** [comment]
I'd need @kkellerlbl to comment - I'm not sure where he was when we were taken off auth. I really wish he'd been given time to finish up what he was doing...

**Comment by mlhenderson** [comment]
@msneddon The handle_service repo does contain an hsi.sql file, https://github.com/kbase/handle_service/blob/master/hsi.sql.  

@msneddon It is not clear if @kkellerlbl's PR would be harmful or not.  It does not change any auth that I could see, but it did introduce dependency on kb-sdk, and removed ids_to_handles.  If the auth code changes, yes this would definitely impact this repo and container.

**Review by msneddon — APPROVED** [review]

**Comment by msneddon** [comment]
All looks good then.  Doesn't look like I have permission to accept the PR, but looks fine to merge now.

**Pull request merged**
